### ISSUE TITLE
Crash when playing

### ISSUE THREAD

**Issue by dann1kid** [G3rste/petai#1]
No any actions with pets but crashes

```

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PetAI.EntityBehaviorTameable.disobey(Single intervall)
   в Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   в Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   в Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   в _rnlVSzJ2AGPu2719D3re8Z7kN2c._iCctvUrJRYdSyJrBVxt5h8N0k5h(Single )
   в _o0lbNJXQO06me4d8j661Kh7y0zO._HmSBpw6fP4XFLEcv29tc0ifOKYvb(Single )
   в _o0lbNJXQO06me4d8j661Kh7y0zO._3U99eoPu0PaDLPVrL8tfzH5UDEJ(Single )
   в Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   в OpenTK.GameWindow.DispatchRenderFrame()
   в OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   в _M48MnHH5BAvHUzcYoEuchRW0acb._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(_UGHNIsOGTJBe1BTRXYmLwHTbmS , String[] )
   в _xNqQDGqRsRSMIeuzt2MHKQHDzSd._e0atQ8VmmvgBK7zb3Yh4iDqOiHY(ThreadStart )

**Comment by G3rste** [comment]
What pets did you have enabled when the error occurred?
Have you been near wild wolfes when it happened?

**Comment by G3rste** [comment]
Are you playing on a server or are you playing singleplayer?

**Comment by dann1kid** [comment]
> What pets did you have enabled when the error occurred? Have you been near wild wolfes when it happened?

Yes, wolves are nerby. Default settings, no switching

**Comment by dann1kid** [comment]
> Are you playing on a server or are you playing singleplayer?

MP

**Comment by G3rste** [comment]
> > Are you playing on a server or are you playing singleplayer?
> 
> MP

Did just your client crash or did the whole server crash?
And did the error occur in the previous version too (only if you played the previous version ofc)?

**Comment by dann1kid** [comment]
> > > Are you playing on a server or are you playing singleplayer?
> > 
> > 
> > MP
> 
> Did just your client crash or did the whole server crash? And did the error occur in the previous version too (only if you played the previous version ofc)?

No previous version, crash on client side only

**Comment by dann1kid** [comment]
Any test else?

**Comment by G3rste** [comment]
> No previous version, crash on client side only

Thanks, this should be the crucial bit of information.

I am currently at work (and will be for the next 7 hours or so), so fixing the issue sadly will take me a couple of hours

**Comment by dann1kid** [comment]
> > No previous version, crash on client side only
> 
> Thanks, this should be the crucial bit of information.
> 
> I am currently at work (and will be for the next 7 hours or so), so fixing the issue sadly will take me a couple of hours

Okay, if any help just write me

**Comment by G3rste** [comment]
[petai_v1.0.2.zip](https://github.com/G3rste/petai/files/7590221/petai_v1.0.2.zip)
Does this solve the issue?

**Comment by dann1kid** [comment]
> 

Will test tommorrow
