### ISSUE TITLE
Suggestion: Pet Renaming

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#11]
Many reasons, from mistyping to not knowing the sex or color of the pup. Ability to rename would be great. Even if it was locked behind an obedience level.

**Comment by G3rste** [comment]
Are you interested in testing this out? There should be a small button on the top right of the command interface to let you check and change some stats of your pet.
[petai.zip](https://github.com/G3rste/petai/files/7998035/petai.zip)

**Comment by RogueRaiden** [comment]
1. The rename GUI appears behind the command GUI when you press the button.

2. The X button and Fixable/Movable button clickable area offset from visuals.

3. If you press the "rename" button twice, the rename GUI turns black when you close it

4. Cats don't have a reproduce toggle

**Comment by G3rste** [comment]
Thanks for the quick test.
I think I can fix 1-3 by simply closing the command GUI when the profile GUI is opened 
4. is expected behavior. As of now, I have no model for baby cats, so they can not reproduce yet.
The Toggle should only appear if a pet can reproduce do avoid confusion

**Comment by RogueRaiden** [comment]
Ahh, just need a kitten then ;)
