### ISSUE TITLE
Suggestion: Have pets respawn on the owner's spawn point

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#15]
Playing on a server using the mod for a while now. Seems there might be an issue with the pets respawning on the server. Either the pets are respawning while players are running around and losing the animal or the pets do not respawn while the player is offline. Either way, we're starting to lose our pets lol

**Comment by G3rste** [comment]
You could turn off pets respawning on their own and make them revivable via the config file in VintageStoryData/ModConfig/petconfig.json.

- default:

```json
  "respawningPets": [
    "tame-wolf-male",
    "tame-wolf-female",
    "tame-wolf-pup"
  ],
  "petResurrectors": [
    {
      "itemCode": "gear-temporal",
      "healingValue": 15.0
    }
  ]
```

- This should make your pets die and let them be revived via temporalgear (You can of course use any item you like):

```json
  "respawningPets": [ ],
  "petResurrectors": [
    {
      "itemCode": "gear-temporal",
      "healingValue": 15.0
    }
  ]
```

**Comment by RogueRaiden** [comment]
ahh, i see they poof away instantly if they can respawn but lay around dead if they cannot. Just seems to be an issue with the respawning sometimes not working.
