### ISSUE TITLE
server performance

### ISSUE THREAD

**Issue by cyraxan** [G3rste/petai#21]
Pets AI sometimes producing lag spikes on populated server and sometimes it's look like short, ~500ms, setbacks of character in moving
Is there's anyway in config to reduce AI CPU load?

09:09:04 [Server Warning] Server overloaded. A tick took 520ms to complete.
09:09:04 [Server Notification] A tick took 523,74ms
entity-ai-tasks-tick-start-execPetAI.AiTaskPetSeekEntity: 281,88ms
entity-ai-tasks-tick-start-execVintagestory.GameContent.AiTaskSeekEntity: 157,36ms
entity-ai-tasks-tick-cont-PetAI.AiTaskPetSeekEntity: 29,35ms
entity-controlledphysics-end: 16,55ms
testspawn game:dragonfly-brownhawker: 8,59ms
entity-done-bh-repulseagents: 4ms
gmleVintagestory.Server.ServerSystemEntitySimulation: 2,54ms
end: 1,97ms

15.2.2022 16:07:54 [Notification] A tick took 751.45ms
entity-ai-tasks-tick-start-execPetAI.AiTaskPetSeekEntity: 535.46ms
gmlewildcraft.BlockEntityWCBerryBush: 74.69ms
gmlePrimitiveSurvival.ModSystem.BETreeHollowGrown: 30.09ms
entity-controlledphysics-end: 18.04ms
gmleUsefulStuff.BEWelcomeMat: 17.86ms
gmleVintagestory.GameContent.BlockEntityBerryBush: 14.62ms
gmleVintagestory.Server.ServerSystemBlockSimulation: 9.89ms
testspawn game:dragonfly-brownhawker: 9.11ms

**Comment by G3rste** [comment]
I feared that this might become an issue some day...
Do you have any specific information as to when the tasks are getting expensive?
Is it when currently fighting? What aggressionlevel are the lagging pets set to?
How many pets/ player are there on the server?

**Comment by G3rste** [comment]
Does this fix the performance issues without changing the pet behavior too much? 

[petai.zip](https://github.com/G3rste/petai/files/8084095/petai.zip)

**Comment by cyraxan** [comment]
Tested [petai.zip](https://github.com/G3rste/petai/files/8084095/petai.zip) on test server, still PetAI top tick consumer on server
Didn't tested pet behavior and client setbacks, no changes really noticed.

```
13:01:51 [Server Notification] A tick took 495.87ms
entity-ai-tasks-tick-start-execPetAI.AiTaskPetSeekEntity: 336.37ms
entity-done-bh-air: 83.22ms
entity-done-bh-harvestable: 34.29ms
entity-done-bh-emotionstates: 8.4ms
entity-controlledphysics-end: 6.89ms
entity-done-bh-repulseagents: 5.02ms
ss-tick-Vintagestory.Server.ServerSystemSendChunks: 4.19ms
gmleVintagestory.GameContent.EntityPartitioning: 2.66ms
```
Not sure, are the wild and domesticated animals are involved in counting PetAI ticks

**Comment by G3rste** [comment]
I have not played around with this myself. But sseing your First diagram I figured that petseekentity is around double the cost to the base task.
Could you test with same amounts of pets and wild creatures (best would probably be wolves against dogs)? That would be the best way of comparing AiTaskPetSeekEntity to AiTaskSeekEntity. Or you could install it on your server. The changes are only server side so the other players do not need to change anything.

If this does not help, I will have to do more drastical things to decrease lag...

**Comment by G3rste** [comment]
New snapshot version with further optimization.
[petai_snapshot.zip](https://github.com/G3rste/petai/files/8102157/petai_snapshot.zip)

**Comment by cyraxan** [comment]
could not see any differences even with [petai_snapshot.zip](https://github.com/G3rste/petai/files/8102157/petai_snapshot.zip) on server, still server overloaded and PetAI on top
```
19.2.2022 21:15:23 [Notification] A tick took 751,46ms
entity-ai-tasks-tick-start-execPetAI.AiTaskPetSeekEntity: 374,47ms
entity-done-bh-air: 91,88ms
entity-controlledphysics-end: 77,88ms
entity-ai-tasks-tick-start-execFarmlife.AiTaskTweakedSeekFoodAndEat: 66,24ms
entity-ai-tasks-tick-cont-PetAI.AiTaskPetSeekEntity: 35,81ms
entity-ai-tasks-tick-start-execVintagestory.GameContent.AiTaskMeleeAttack: 19,4ms
entity-done-bh-repulseagents: 15,98ms
gmleVintagestory.Server.ServerSystemEntitySimulation: 15,8ms

```

**Comment by G3rste** [comment]
How many entities are we talking about here?
What are their aggressionlevels? 

When testing in Singleplayer I can not achieve numbers close to this?
Ist it still a problem if you disable farmlife? It also has an [AiTaskPetSeekEntity](https://github.com/91loocekaj/vs-farmlife/blob/main/src/AI/AiTaskPetSeekEntity.cs)

**Comment by cyraxan** [comment]
![image](https://user-images.githubusercontent.com/34022944/154818377-d3b32776-b902-4535-bd6e-ffc9f056e90e.png)
like that
that's is not creative made test farm, it's seems to be bug of farmlife mod

**Comment by G3rste** [comment]
Hm these animals should not even be treated as pets by my mods.
Or maybe its because my "should attack" check is more expensive than the base games and there are to many piglins in the enclosure?

There is not much more I can to as of now, I will leave this open for more testresults though.
