### ISSUE TITLE
Unable to spawn in pet mobs in creative on server

### ISSUE THREAD

**Issue by MeghanBomberger** [G3rste/petai#22]
This may or may not be a PetAI issue, but I noticed cats, horse, and dogs are missing from inventory in creative mode on our server. When loading the current set of mods and current save file into single player they show up fine. Since the animals from all three of the pet mods we are using were missing my best guess was the issue was central to PetAI. Is this a bug or am I just missing a setting somewhere?

Mod versions currently using of each are:
PetAI 1.3.5
Cats 1.3.3
Feverstone Horses 1.2.5
Wolf Taming 1.3.2

**Comment by G3rste** [comment]
Do you have any other mods installed that might patch some things?
Are there any error logs regarding pets?

When I test (admittedly I only have a singleplayer run for testing right now) everything seems fine.
![creative-items](https://user-images.githubusercontent.com/66719048/156663503-e04d92cb-27de-4390-85e9-966d0e382602.png)

**Comment by RogueRaiden** [comment]
Creative mode on my test server with a lot of mods and the creatures are listed just fine
