### ISSUE TITLE
Pets seem to be rather expensive with ticks

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#26]
**looks like the pets AI tasks are rather high in tick usage. just a snip, longer tick profiling in document**

16:28:05 [Server Warning] Server overloaded. A tick took 526ms to complete.
16:28:05 [Server Notification] A tick took 528.65ms
entity-ai-tasks-tick-start-execPetAI.AiTaskPetSeekEntity: 208.09ms
entity-ai-tasks-tick-start-execPetAI.AiTaskSeekNest: 141.38ms

[PetsTickLog.txt](https://github.com/G3rste/petai/files/8310084/PetsTickLog.txt)

On my own, I tested with making the sleeping task happen almost constantly and for much longer and that reduced the load quite a bit. minor edits though just for testing.

**Comment by RogueRaiden** [comment]
#21 
just saw this. have been testing this actually since before that newer version. doesnt seem to have made much difference honestly. im going to test by removing the seek entity and nest AI tasks for now.

i have a testing server you can use if needed. just let me know

**Comment by G3rste** [comment]
I had another idea on what could be causing the bad performance.
The previous versions do a lot of player lookups to find the owner of a pet during these tasks.

I hope this improves performance at least for the seekentity task
[petai.zip](https://github.com/G3rste/petai/files/8311581/petai.zip)

If this still does not do the trick, I could really use the test-server you have.

**Comment by RogueRaiden** [comment]
join my discord, send me a message and i'll get you the test server info
https://discord.gg/bxeGxWmcae
