### ISSUE TITLE
suggestion for the config: Add a generation of x creature to factor in/modulate tamable/obediance increase/decrease or threshold for certain commands

### ISSUE THREAD

**Issue by Aledark789** [G3rste/petai#28]
suggestion for the config: Add a generation of x creature to factor in/modulate tamable/obediance increase/decrease or threshold for certain commands

In short a gen 5 horse could get tamed easier and maintain their tamable/obedience longer while a gen 0 or 1 would be longer to tame and rise obedience.

Maybe have it consider it from gen 0 to 10 and put a true/false to factor in
which would affect
tamability increase
obedience increase
tamability decrease over-time
obedience decrease over-time

Also could put a cap on how many pet can be tamed, named by server settings?

Thanks!

**Comment by RogueRaiden** [comment]
A tame cap would be wonderful, actually
