### ISSUE TITLE
[Suggestion] Ridable pets

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#40]
An entity riding system, flagged like "size" in the json as maybe "ridable" or "mountable": true/false. Perhaps a saddle equipped to the creature is required to mount, with a high enough obedience level.

Would pair perfectly with this being a pet library and the already existing equipment system.

**Comment by G3rste** [comment]
There already is a (arguably pretty bare bone) [riding system](https://github.com/G3rste/petai/blob/main/src/Entity/EntityMount.cs) in this mod.
It is utilized by the [feverstone horses](https://mods.vintagestory.at/feverstonehorses) mod

**Comment by RogueRaiden** [comment]
ohh really? i assumed they did that on their own. Thanks! i'll be checking it out now then.
