### ISSUE TITLE
[Suggestion] Pet PvP protection

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#45]
Some sort of toggleable protection for pets from player damage would be very nice. Per player or globally.

Have had a couple issues with players killing pets, nothing too severe. 

Temporary actions were taken by removing the ability to harvest the pets.

**Comment by G3rste** [comment]
Next version will have a new config parameter pvpOff. If set to true, players cant damage foreign dogs and vise versa.
I sort of eyeballed this in singleplayer so let me know if it works.

**Comment by RogueRaiden** [comment]
Awesome! We'll definitely do some tests and I'll report any anomalies
