### ISSUE TITLE
Receiving multiple damage until instant death

### ISSUE THREAD

**Issue by betterdayz306** [G3rste/petai#47]
Hey ,
I have a weird bug that makes the gaming experience awful. Everytime i get damage from another entity its multi-hits. Like So many that I die. And it doesnt matter which creature it is.

Example One: I have 30 HP and want to kill a Aurochs. The animation of the Aurochs shows that it hit´s me once but i instantly die. The Damage Log later shows 11 times damage (its 3hp per hit, i reduced it in world configs).
Example Two: I have no food left and am starving. The HP bar reduces within a few seconds.

Now i know for sure that this is not normal behavior so I quickly figuered that it has something to do with mod interference.

So i started a new world and did some testing. I ultimatly found that this mod caused the problem.  After i deactivated it everything worked fine. Now i´m sure that its a interference with other mods but I can´t figure out how to find a solution. 

Abstract of the damage log:
----
1.6.2023 12:06:16 [Chat] Welcome betterdayz, may you survive well and prosper @ 0
1.6.2023 12:07:22 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:22 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Lost 3 hp by an angry Aurochs (Creature) @ -5
1.6.2023 12:07:23 [Chat] Player betterdayz got killed by an angry Aurochs @ 0
1.6.2023 12:07:28 [Chat] You have re-emerged at your returning point. It will vanish after 99 more uses @ 0
1.6.2023 12:07:28 [Chat] Gained 30,53 hp through heal @ -5
----

Please let me know if I can submit any other logs that would be helpful.

Cheers and thanks in advance

**Comment by G3rste** [comment]
Hm I dont know what could be causing this
Can you reproduce your error with only petai and wolftaming enabled without any other mods?
If not, what other mods do you need to reproduce the error?

**Comment by betterdayz306** [comment]
Hey thanks for your reply and the awesome work you're doing for the community!

I made a post on the VS Forum
https://www.vintagestory.at/forums/topic/10913-receiving-multiple-damage-until-instant-death-edit-2/

Another user mentioned the same behavior but without your mods. Now while adding your mods leads to this issue, it's not exclusively. So the problem seems to occur by an interference with another mod but I can't identify it exactly. 
If you follow the link you will find the variety of mods that I use. 
You are free to close this issue but I'd appreciate any help if you got an idea.

Cheers :)
