### ISSUE TITLE
[Suggestion] a craftable Pet Pod that is basically a PokeBall for your pets

### ISSUE THREAD

**Issue by RogueRaiden** [G3rste/petai#50]
Something a lot of players have trouble with is moving the pets long distances. Especially with low obedience. Sometimes they get lost while traveling by getting stuck on something or falling into caves. I think a Pet Pod, something that can store only pets would be a nice addition.

**Comment by G3rste** [comment]
What about using animalcages for that? Every[ pet should go into the cage without the need to hurt it](https://github.com/G3rste/animalcages/blob/main/src/BlockMediumCage.cs#L71C86-L71C86) even if its generation zero

**Comment by RogueRaiden** [comment]
Is it setup so that a pet can only be captured by the owner? After some thinking, that one thing should be all i need.

So that pets cannot simply be stolen.

**Comment by RogueRaiden** [comment]
Also, does it allow every "pet" regardless of the animal?

**Comment by G3rste** [comment]
> Is it setup so that a pet can only be captured by the owner? After some thinking, that one thing should be all i need.
> 
> So that pets cannot simply be stolen.

- For the pets in the medium category that should be the case. There I check if the animal is hurt, has a generation greater than 0 or is owned by the player that is holding the cage. If one of these evaluates to true, the animal is catchable.

> Also, does it allow every "pet" regardless of the animal?

- Only the ones that are located in the animalcages config files

**Comment by RogueRaiden** [comment]
Gotcha, thanks for the help! Think this will be perfect
