### ISSUE TITLE
Riding animation unusable.

### ISSUE THREAD

**Issue by Dark-Thoughts** [G3rste/petai#57]
The riding animation in 1.19 is completely borked and makes mods using it, like Feverstone Horses, unusuable.
![image](https://github.com/G3rste/petai/assets/15324196/42f3e9bb-a495-45e6-80b9-e4d1d219958f)

**Comment by G3rste** [comment]
Should be better with [v2.2.3](https://github.com/G3rste/petai/releases/tag/v2.2.3).
