### ISSUE TITLE
Food does not work as taming-treat

### ISSUE THREAD

**Issue by Sythelux** [G3rste/petai#58]
I'm working on a Mod to tame bears: https://gitlab.com/Sythelux/apanserbjornstory

I have struggle to set Things that the Player can eat as tame-food for the pet for example honeycombs and berries, as my player character wants to rather eat it himself then to give it to the pet. I'm not sure if it is a bug, or if I have to patch something very specific, which I'm just not aware of.

**Comment by G3rste** [comment]
It can be patched, sadly I only did it for one type of food so far.
I created a [small patch for vegetables](https://github.com/G3rste/petai/blob/main/resources/assets/petai/patches/itemtypes/vegetable.json) to circumvent this problem.
You could do the same patch for honey and berries in your mod.

Let me know if this works for you.

**Comment by Sythelux** [comment]
I got it to work:
with fruit: https://gitlab.com/Sythelux/apanserbjornstory/-/blob/main/APanserbjornStory/assets/apanserbjornstory/patches/itemtypes/food/fruit.json?ref_type=heads

and with honeycomb: https://gitlab.com/Sythelux/apanserbjornstory/-/blob/main/APanserbjornStory/assets/apanserbjornstory/patches/itemtypes/resources/honeycomb.json?ref_type=heads

you could actually add fruit to the lib because that could become relevant for other mods for taming pigs, or sheep maybe. The honeycomb could just stay here as lookup, but the issue itself is closed. Thank you.
